language: node_js
sudo: false
services:
- mongodb
node_js:
- '4.2'
notifications:
  slack:
    secure: AmObJ8NeIDZbEEjnChLEfaceZd1ERXTD6yG62yaPLTjwnBKB08v1k8hlRU5bqPmu9i+viDSoqcVCqxKlIzmoGCJq2TaagtmRYmZGufHpn9hGHmLlVTW2rLUVjaHqlMQKspngu0dk/lVPHncLzGQei1+Q7g2c+VDrzDtx+nF7aMIroDEveyssbJtqPxoVPuM+rX0Tit7Qtv0P1FPDpQPU06HwYCOh2bSwF4u7OxvrTAaj+y7Dvt4hzl9wd9QktqRLyOeN6Az507nvjAHIuRtOYBISrgsjv78qGEepalqvgSEcvqagl80rgswgHjP264W06O0s0Ou6zvm70gXEBUaK9woxxZXVwiVxtX+OxhJh8p1CgsM3w3C4xnjmX2zWSeYnNErNINeBEJU7VYIDRsn0Q8mzNuC3FmyAkJk0IER6+MJ+Ja+c4SdOtdJ4Cn7BtBoRPCT88kQuT0ju++BVZZvMwQbdd9ZrabMDBlJMKqfqVOQ1bbC8Vz+U1qvNFoEVW97k4+bjmT12lh2wrTkOTI9Bne0BaZDKj8K4k262U+UxWiWMxKuEm4hIR+K3fjM8QY82O+ty4IXL5gqfQrsK8lXIzjsq/WhZutRmLS6GxLAfJNbS+1AxvWEJy8oKxjsJSZULNX6Z19qmboz8ZUFkgqiUJO9eJlk9v+HiXuMqkNCYd5s=
    on_success: change
    on_failure: always
